### PR TITLE
Add option to limit tests to specific files

### LINKED ISSUE #27: Make unit tests compatible with Python 3.11
Some of the unit tests fail when run with Python 3.11.  For example, the `assertRegex` here

https://github.com/openelections/openelections-data-tests/blob/e58e494bdf03638b776674efc00eb12aedacb8fc/tests/test_data_tests.py#L243

passes in 3.10 but fails in 3.11.  We should investigate what is causing this failure and update the tests accordingly.

### PR DESCRIPTION
**Pull request by warwickmm**
This adds an option to limit the tests to specific files.  This will allow us to create new workflows that
1. Test just the files that were added in a pull request.
2. Automatically comment on a pull request to raise potential issues in the new files.

These will hopefully make it easier for us to catch and address issues earlier upon submission rather than later.  The submitter may have more insight about the data than someone examining the data afterwards.

A future direction of improvement can be to run the tests on modified files as well, but that will require a bit more work.

### CODE REVIEW

**Comment by warwickmm** [comment]
See [here](https://github.com/warwickmm/openelections-data-ca/pull/3) for an example of the automatic commenting.  @dwillis, let me know if you think this is unnecessary.  We can limit the scope to just the new workflow without the automatic comments if that's preferred.  I sometimes find the workflow logs difficult to navigate, which is what led me to this approach.

**Comment by warwickmm** [comment]
I'll need to investigate why the tests are failing.  They run fine for me locally.  I'll mark this as a draft and reopen when it's ready.

**Comment by dwillis** [comment]
I think this is a great approach, @warwickmm

**Comment by warwickmm** [comment]
For some reason, some of the unit tests fail with Python 3.11.  For now, I've frozen the version to 3.10 until I can debug this more easily (I don't have 3.11 available on my machine).  I created #27 to keep track of this.

**Comment by warwickmm** [comment]
I was able to fix the unit tests.  @dwillis, this is ready for review.

**Pull request merged**
